### ISSUE TITLE
Game over condition(cross pattern)

### ISSUE THREAD

**Issue by tsu-nera** [nczempin/gym-tic-tac-toe#1]
Hello, I enjoy playing with this game, and I have a question.

In game over [condition](https://github.com/nczempin/gym-tic-tac-toe/blob/master/gym_tic_tac_toe/envs/tic_tac_toe_env.py#L37), How about checking "cross condition", like [this](https://en.wikipedia.org/wiki/Tic-tac-toe#/media/File:Tic_tac_toe.svg).

I mean, "cross condition" are
`(board[0] == p and board[4] == p and board[8] == p)`
and
`(board[2] == p and board[4] == p and board[6] == p)`

Thank you.

**Comment by nczempin** [comment]
yes; the game is very unfinished; feel free to provide a PR

**Comment by tsu-nera** [comment]
Thank you for merging #2.
I'm relieved and glad because it is my first time to provide PR in my life!
You kindly reviewed my PR.
